title: "Zakiy Fadhil Muhsin"
email: zakiy@eviterstudio.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: id_ID
lang: id_ID
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  zakiyfadhilmuhsin:
    name: Zakiy Fadhil Muhsin
    display_name: Zakiy Fadhil Muhsin
    avatar: 'assets/images/sal.png'
    email: zakiy@eviterstudio.com
    web: https://zakiyfadhilmuhsin.github.io
    twitter: https://twitter.com/zakiyfadhilm
    description: "Penggiat Teknologi dan Bisnis"

# Social
social:
  instagram: https://www.instagram.com/zakiyfadhilmuhsin/
  facebook: https://www.facebook.com/zakilah24
  twitter: https://twitter.com/zakiyfadhilm

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives